package sandra.com.starwarsapp

const val CATEGORY_BUNDLE_KEY = "CATEGORY_BUNDLE_KEY"
const val CATEGORY_BUNDLE_DEFAULT = 0

const val FILM_BUNDLE_KEY = "FILM_BUNDLE_KEY"
const val PEOPLE_BUNDLE_KEY = "PEOPLE_BUNDLE_KEY"
const val PLANET_BUNDLE_KEY = "PLANET_BUNDLE_KEY"
const val SPACESHIP_BUNDLE_KEY = "SPACESHIP_BUNDLE_KEY"
const val VEHICLE_BUNDLE_KEY = "VEHICLE_BUNDLE_KEY"
const val SPECIES_BUNDLE_KEY = "SPECIES_BUNDLE_KEY"

enum class CATEGORIES(val id: Int) {
    FILMS(0),
    PEOPLE(1),
    PLANETS(2),
    SPACESHIPS(3),
    VEHICLES(4),
    SPECIES(5)
}